export const dummyData = [
        {
          id: 1,
          title: "How to Improve Your Skills in League of Legends",
          keyword: "league of legends [2240000]",
          words: 4575,
          createdOn: "20 hours ago",
        },
        {
          id: 2,
          title: "How to Master Last Hitting in League of Legends",
          keyword: "league of legends [2240000]",
          words: 3480,
          createdOn: "21 hours ago",
        },
        {
          id: 3,
          title: "7 Tips for Better Teamplay in League of Legends",
          keyword: "league of legends [2240000]",
          words: 2676,
          createdOn: "a day ago",
        },
        {
          id: 4,
          title: "Top Virtual Executive Assistant Services (2024)",
          keyword: "virtual executive assistant [2900]",
          words: 2408,
          createdOn: "1 Oct, 24",
        },
        {
          id: 5,
          title: "Unlimited Graphics Design Solutions",
          keyword: "unlimited graphic design services [390]",
          words: 1703,
          createdOn: "--",
        },
        {
          id: 6,
          title: "Top Amazon Payment Methods For Quick Access to Funds",
          keyword: "amazon payment methods [3600]",
          words: 2647,
          createdOn: "--",
        },
        {
          id: 7,
          title:
            "Backlinks 101: What are backlinks and why they're important [Free template]",
          keyword: "backlinks [810]",
          words: 2261,
          createdOn: "--",
        },
        {
          id: 8,
          title: "7 Leading AI SEO Tools in 2024 (Ranked & Compared)",
          keyword: "ai seo software [880]",
          words: 1543,
          createdOn: "--",
        },
        {
          id: 9,
          title: "Unlimited Graphic Design Services You Can Rely On",
          keyword: "unlimited graphic design services [390]",
          words: 1074,
          createdOn: "--",
        },
      ];